# batch_bins: 16000000
# batch_bins: 40000000
# batch_bins: 320000000
accum_grad: 1
max_epoch: 250
patience: 10
num_workers: 0
# The initialization method for model parameters
init: xavier_uniform
# batch_type: numel

loaders:
    speech:
        repeat: 1
        batch_size: 8
        # batch_bins: 16000000
    text:
        repeat: 0
        batch_size: 8
        # batch_bins: 16000000
    speech_valid:
        repeat: 1
        batch_size: 2
        # batch_size: 8
        # batch_bins: 16000000

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: transformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

text_encoder: transformer
text_encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: embed
    normalize_before: true
    padding_idx: 2

shared_encoder: transformer
shared_encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 0
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: identity
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    text_in_mask_ratio: 0.2
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

frontend_conf:
  n_fft: 512
  hop_length: 256

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
